# Generated by Django 5.0.2 on 2024-11-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordendespacho',
            fields=[
                ('id_orden', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('estado_envio', models.CharField(max_length=50)),
                ('metodo_envio', models.CharField(max_length=100)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('correo_cliente', models.CharField(max_length=255)),
                ('telefono_cliente', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion_envio', models.CharField(max_length=255)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordendespacho',
                'managed': False,
            },
        ),
    ]
