# Generated by Django 5.0.2 on 2024-08-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
