# Generated by Django 5.0.2 on 2024-08-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_comuna_options_alter_genero_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
