# Generated by Django 5.0.2 on 2024-08-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
