# Generated by Django 5.0.2 on 2024-10-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_problema_table_alter_respuesta_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='EstadoLibro',
        ),
    ]
