# Generated by Django 5.0.2 on 2024-10-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_authgrouppermissions_delete_estadolibro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialAuthAssociation',
        ),
        migrations.DeleteModel(
            name='SocialAuthCode',
        ),
        migrations.DeleteModel(
            name='SocialAuthNonce',
        ),
        migrations.DeleteModel(
            name='SocialAuthPartial',
        ),
        migrations.DeleteModel(
            name='SocialAuthUsersocialauth',
        ),
    ]
